-- DATABASE
CREATE DATABASE OPENLACANDON
	WITH
	OWNER = postgres
	ENCODING = 'UTF8'
	LC_COLLATE = 'en_US.utf8'
	LC_CTYPE = 'en_US.utf8'
	TABLESPACE = pg_default
	CONNECTION LIMIT = -1
	TEMPLATE template0;


-- CLIENT TABLE
CREATE TABLE CLIENT
(
	-- PRIMARY KEY
	ID SMALLSERIAL PRIMARY KEY NOT NULL,

	-- ACCOUNT INFO
	USERNAME VARCHAR(64) UNIQUE NOT NULL,
	PASSWORD VARCHAR(64) NOT NULL,
	EMAIL VARCHAR(64) UNIQUE NOT NULL,
	PLUS BOOL DEFAULT FALSE,
	WALLET_BALANCE INTEGER DEFAULT 0,

	-- USER INFO
	FIRST_NAME VARCHAR(64) DEFAULT NULL,
	LAST_NAME VARCHAR(64) DEFAULT NULL,
	TEL BIGINT DEFAULT NULL,

	-- ADDRESS INFO
	ADDRESS VARCHAR(128) DEFAULT NULL,
	CITY VARCHAR(64) DEFAULT NULL,
	ZIP INTEGER DEFAULT NULL,
	COUNTRY VARCHAR(64) DEFAULT NULL
);

-- CLIENT EXAMPLES
INSERT INTO CLIENT VALUES(DEFAULT, 'ANGEL', '123', 'angel.storres@alumnos.udg.mx');
INSERT INTO CLIENT VALUES(DEFAULT, 'CHRISTIAN', '678', 'christian.delacruz1289@alumnos.udg.mx');
INSERT INTO CLIENT VALUES(DEFAULT, 'DAMIAN', '567', 'angel.garcia9106@alumnos.udg.mx');
INSERT INTO CLIENT VALUES(DEFAULT, 'STALIN', '123', 'stalin.mendoza7428@alumnos.udg.mx');

-- BOOK TABLE
CREATE TABLE BOOK
(
	-- PRIMARY KEY
	ISBN SMALLSERIAL PRIMARY KEY NOT NULL,

	-- BOOK INFO
	TITLE VARCHAR(64) NOT NULL,
	AUTHOR VARCHAR(64) NOT NULL,
	GENRE VARCHAR(64) DEFAULT NULL,
	SYNOPSIS VARCHAR(256) DEFAULT NULL,
	RATING SMALLINT DEFAULT 0 NOT NULL,
	IMAGE_FRONT BYTEA DEFAULT NULL,
	IMAGE_BACK BYTEA DEFAULT NULL
);

-- BOOK EXAMPLES
INSERT INTO BOOK VALUES(DEFAULT, 'The Martian Chronicles', 'Ray Bradbury');
INSERT INTO BOOK VALUES(DEFAULT, 'Fairy Tale', 'Stephen King');
INSERT INTO BOOK VALUES(DEFAULT, 'Harry Potter and the Sorcerers Stone', 'J.K Rowling');
INSERT INTO BOOK VALUES(DEFAULT, 'The Divine Comedy', 'Dante Alighieri');

-- FORMAT TABLE
CREATE TABLE FORMAT
(
	-- PRIMARY KEY
	ID SMALLSERIAL PRIMARY KEY NOT NULL,

	-- FOREIGN KEY
	ISBN SMALLINT REFERENCES BOOK(ISBN) NOT NULL,

	-- INFO
	PRICE_LIST MONEY DEFAULT 0 NOT NULL,
	TYPE VARCHAR(64) DEFAULT 'Kindle' NOT NULL,
	PAGES SMALLINT DEFAULT 0 NOT NULL,
	STOCK SMALLINT DEFAULT -1 NOT NULL
);

-- FORMAT EXAMPLES
INSERT INTO FORMAT VALUES(DEFAULT, 1, 90, 'Kindle', 140, -1);
INSERT INTO FORMAT VALUES(DEFAULT, 1, 265, 'Pasta blanda', 120, 55);
INSERT INTO FORMAT VALUES(DEFAULT, 1, 640, 'Pasta dura', 175, 30);
INSERT INTO FORMAT VALUES(DEFAULT, 2, 250);
INSERT INTO FORMAT VALUES(DEFAULT, 3, 370, 'Pasta dura', 490, 90);
INSERT INTO FORMAT VALUES(DEFAULT, 4, 120, 'Kindle', 385, -1);

-- ORDER TABLE
CREATE TABLE ORD
(
	-- PRIMARY KEY
	ID SMALLSERIAL PRIMARY KEY NOT NULL,

	-- FOREIGN KEY
	ID_CLIENT SMALLINT REFERENCES CLIENT(ID) NOT NULL,

	-- INFO
	DATE_ORDER DATE DEFAULT NOW() NOT NULL,
	DATE_DELIVERY DATE NOT NULL
);

-- ORDER EXAMPLES
INSERT INTO ORD VALUES(DEFAULT, 1, DEFAULT, '2022-09-29');
